name: build frontend microservice

on:
  push:
    branches:
      - main
    paths:
      - frontend_service/*

jobs:

    Docker:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: docker-practice/actions-setup-docker@master

        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

        - name: Create frontend service image
          run: |
            docker build -t regisnobel/frontend_service:$(git rev-parse --short HEAD) -f frontend_service/Dockerfile .
            docker push regisnobel/frontend_service:$(git rev-parse --short HEAD)