name: Setup infrastructure for mailing list app deployment

on:
  workflow_dispatch:

jobs:

  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
        
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible
  
      - name: Verify Ansible Installation
        run: ansible --version
      
      - name: Configure inventory, host and Deploy
        run: |
          cd ansible
          ./make_inventory.sh
          ansible-playbook -i $ANSIBLE_INVENTORY install_docker.yml
          ansible-playbook -i $ANSIBLE_INVENTORY deploy_services.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_INVENTORY: "ansible/inventory.ini"
          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}